In [ ]:
import numpy as np
#陣列運算
a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [ ]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4 , 6, 8, 10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [13]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [16]:
np.random.rand()
np.random.rand(30, 4)

array([[0.72061535, 0.9365843 , 0.64535619, 0.05568109],
       [0.02745994, 0.85346257, 0.35556951, 0.78489834],
       [0.81154273, 0.31648152, 0.46458138, 0.80813143],
       [0.33639226, 0.66218175, 0.5382421 , 0.64227059],
       [0.60787843, 0.59798854, 0.12770741, 0.33922863],
       [0.05668568, 0.4216634 , 0.67799412, 0.12345513],
       [0.89802422, 0.12028786, 0.65517972, 0.03819326],
       [0.18332514, 0.31485686, 0.65995937, 0.65802437],
       [0.68963136, 0.87079689, 0.14326168, 0.54368828],
       [0.12842016, 0.84912961, 0.29731131, 0.91319953],
       [0.82513251, 0.62867945, 0.95151151, 0.96326707],
       [0.54113863, 0.25670845, 0.09996869, 0.14984893],
       [0.73742101, 0.32575787, 0.26928705, 0.0272832 ],
       [0.07794897, 0.81394026, 0.94658796, 0.05488823],
       [0.54956112, 0.73488264, 0.5787312 , 0.75020962],
       [0.73088151, 0.4702547 , 0.76492061, 0.42664743],
       [0.60106738, 0.40146976, 0.80154757, 0.15057966],
       [0.1636925 , 0.35195633,

In [21]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 56,  68,  60,  56,  70],
       [ 55,  85,  53,  72,  78],
       [ 73,  81,  72,  83,  54],
       [ 73,  64,  93,  76,  56],
       [ 99,  84,  66,  68,  99],
       [ 98,  92,  98,  56,  80],
       [ 88,  97,  62,  70,  76],
       [ 70,  99,  83,  85,  95],
       [ 88,  57,  54, 100,  77],
       [ 67,  73,  85,  80,  75],
       [ 79,  68, 100,  96,  61],
       [ 91,  61,  58,  73,  63],
       [ 73,  61,  76,  70,  85],
       [ 65,  58,  75,  75,  99],
       [ 73,  98, 100,  88,  99],
       [ 68,  75,  67,  62,  76],
       [100,  56,  99,  93,  76],
       [ 75,  69,  71,  53,  75],
       [ 61,  99,  71,  55,  59],
       [ 83,  92,  50,  98,  97],
       [ 89,  59,  50,  51,  77],
       [ 52,  86,  70,  80,  88],
       [ 68,  73,  96,  53,  56],
       [ 97,  60,  62,  79,  99],
       [100,  67,  50,  50,  58],
       [ 58,  77,  62,  80,  55],
       [ 76,  94,  78,  55,  98],
       [ 81,  84,  91,  87,  85],
       [ 97,  67,  66,  54,  91],
       [ 80,  