In [2]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個

array([50, 60, 70, 80, 90])

In [7]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 98,  59,  81,  61,  90],
       [ 77,  67,  56,  78,  97],
       [ 74,  82,  50,  55,  75],
       [ 82,  70,  74,  74,  75],
       [ 62,  94,  99,  54,  74],
       [ 99,  84,  56,  51,  84],
       [ 83,  62,  88,  73,  75],
       [ 89,  81,  65,  56,  90],
       [ 81,  68,  99,  52,  56],
       [ 67,  94,  81,  90, 100],
       [ 82,  67,  77,  52,  72],
       [ 83,  86,  94,  56,  51],
       [ 89,  97,  50,  85,  60],
       [ 60,  69,  62,  56,  98],
       [ 81,  85,  53,  87,  63],
       [ 76,  78,  71,  63,  89],
       [ 50,  72,  74,  56,  99],
       [100,  54,  82,  54,  86],
       [ 62,  63,  81,  81,  63],
       [ 72,  78,  52,  85,  95],
       [ 63,  87,  63,  66,  90],
       [ 84,  82,  56,  70,  64],
       [ 68,  58,  89,  69,  76],
       [ 78,  67,  51,  65,  59],
       [ 75, 100,  93,  78,  55],
       [ 96,  56,  98,  66,  75],
       [ 76,  70,  88,  51,  96],
       [ 81,  63,  62,  51,  88],
       [ 71,  74,  54,  71,  53],
       [ 88,  

In [17]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[98, 59, 81, 61, 90]])

In [20]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[98, 59, 81],
       [77, 67, 56],
       [74, 82, 50],
       [82, 70, 74],
       [62, 94, 99]])

In [23]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 81,  56,  50,  74,  99,  56,  88,  65,  99,  81,  77,  94,  50,
        62,  53,  71,  74,  82,  81,  52,  63,  56,  89,  51,  93,  98,
        88,  62,  54,  78,  64,  74,  69,  63,  65,  76,  76,  61,  61,
        62,  60,  90,  64,  97,  77,  80,  78, 100,  70,  75])

In [25]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([389, 375, 336, 375, 383, 374, 381, 381, 356, 432, 350, 370, 381,
       345, 369, 377, 351, 376, 350, 382, 369, 356, 360, 320, 401, 391,
       381, 345, 323, 348, 414, 399, 320, 351, 367, 422, 381, 344, 386,
       385, 338, 382, 345, 435, 357, 396, 367, 436, 385, 424])

In [26]:
total / 5

array([77.8, 75. , 67.2, 75. , 76.6, 74.8, 76.2, 76.2, 71.2, 86.4, 70. ,
       74. , 76.2, 69. , 73.8, 75.4, 70.2, 75.2, 70. , 76.4, 73.8, 71.2,
       72. , 64. , 80.2, 78.2, 76.2, 69. , 64.6, 69.6, 82.8, 79.8, 64. ,
       70.2, 73.4, 84.4, 76.2, 68.8, 77.2, 77. , 67.6, 76.4, 69. , 87. ,
       71.4, 79.2, 73.4, 87.2, 77. , 84.8])

In [29]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([77.8, 75. , 67.2, 75. , 76.6, 74.8, 76.2, 76.2, 71.2, 86.4, 70. ,
       74. , 76.2, 69. , 73.8, 75.4, 70.2, 75.2, 70. , 76.4, 73.8, 71.2,
       72. , 64. , 80.2, 78.2, 76.2, 69. , 64.6, 69.6, 82.8, 79.8, 64. ,
       70.2, 73.4, 84.4, 76.2, 68.8, 77.2, 77. , 67.6, 76.4, 69. , 87. ,
       71.4, 79.2, 73.4, 87.2, 77. , 84.8])

In [31]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([77.8, 75. , 67.2, 75. , 76.6, 74.8, 76.2, 76.2, 71.2, 86.4, 70. ,
       74. , 76.2, 69. , 73.8, 75.4, 70.2, 75.2, 70. , 76.4, 73.8, 71.2,
       72. , 64. , 80.2, 78.2, 76.2, 69. , 64.6, 69.6, 82.8, 79.8, 64. ,
       70.2, 73.4, 84.4, 76.2, 68.8, 77.2, 77. , 67.6, 76.4, 69. , 87. ,
       71.4, 79.2, 73.4, 87.2, 77. , 84.8])